var swabPrefix = 'AHT'; 
var startingSwab = 2;

//mysql -BN -e "select concat('\"', name, '\": {', group_concat(distinct concat('\"', meta_value, '\":\"', post_title, '\"') order by post_title separator ', ' ), '}') from wp_terms t1 inner join wp_term_taxonomy t2 using (term_id) inner join wp_term_relationships using (term_taxonomy_id) inner join wp_posts on ID=object_id inner join wp_postmeta on ID=post_id where post_type='tests' and meta_key='test-code-pm' and parent=115 and post_title not like 'Bundle%' group by term_id, name order by name"
var breedTests = {
	"all": {"CP":"Canine DNA profiles (ISAG 2006) - &pound;30.00"},
	"American Staffordshire Terrier": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Australian Cattle Dog": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Australian Shepherd": {"AC":"Hereditary Cataract", "MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)", "HUU":"Urate Stones - Uric Acid Excretion"},
	"Basset Hound": {"POAG":"Primary Open Angle Glaucoma"},
	"Beagle": {"F7":"Coagulation Factor VII Deficiency", "MLS":"Musladin-Lueke Syndrome", "NCCD":"Neonatal Cerebellar Cortical Degeneration"},
	"Bedlington Terrier": {"CT":"Copper Toxicosis"},
	"Boerboel": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Border Collie": {"BC_MX":"Combined Test - IGS (Vitamin B12 Deficiency) Sensory Neuropathy and Trapped Neutrophil Syndrome", "IGS":"Imerslund-Gräsbeck Syndrome (Vitamin B12 Deficiency)", "MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)", "SN":"Sensory Neuropathy", "TNS":"Trapped Neutrophil Syndrome"},
	"Boston Terrier": {"BJ":"Early Onset Hereditary Cataracts"},
	"Briard": {"CON-STA-NI-BL":"Congenital Stationary Night Blindness"},
	"Bulldog": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Cavalier King Charles Spaniel": {"CC_and_EF":"Combined Test - Curly Coat Dry Eye and Episodic Falling", "CC":"Curly Coat Dry Eye", "EF":"Episodic Falling"},
	"Chinese Crested": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Dachshund (Miniature Long Haired)": {"EP":"Progressive Retinal Atrophy (cord1)"},
	"Dachshund (Miniature Smooth Haired)": {"EP":"Progressive Retinal Atrophy (cord1)"},
	"Dachshund (Miniature Wire Haired)": {"EP":"Progressive Retinal Atrophy (cord1)", "PRO-RET-ATR-NHPH4":"Progressive Retinal Atrophy CRD (NHPH4)"},
	"Dachshund (Standard Wire Haired)": {"PRO-RET-ATR-NHPH4":"Progressive Retinal Atrophy CRD (NHPH4)"},
	"Dalmatian": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"English Shepherd": {"MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)"},
	"Finnish Lapphund": {"PMP":"Pompe Disease"},
	"Fox Terrier (Wire)": {"P-LENS-LUX":"Primary Lens Luxation"},
	"French Bulldog": {"AC":"Hereditary Cataract"},
	"German Shepherd Dog": {"MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)", "HUU":"Urate Stones - Uric Acid Excretion"},
	"Giant Schnauzer": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Golden Retriever": {"GR_PRA1":"Progressive Retinal Atrophy 1", "GR_PRA2":"Progressive Retinal Atrophy 2"},
	"Gordon Setter": {"RCD4":"Progressive Retinal Atrophy (rcd4)"},
	"Hungarian Vizsla (Smooth-Haired)": {"CD":"Cerebellar Ataxia"},
	"Hungarian Wire Haired Vizsla": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Irish Red &amp; White Setter": {"CL":"Canine Leukocyte Adhesion Deficiency", "IS":"Progressive Retinal Atrophy (rcd1)", "SV":"Von Willebrands Disease"},
	"Irish Setter": {"CL":"Canine Leukocyte Adhesion Deficiency", "IS":"Progressive Retinal Atrophy (rcd1)", "RCD4":"Progressive Retinal Atrophy (rcd4)"},
	"Italian Spinone": {"CA":"Cerebellar Ataxia"},
	"Jack Russell Terrier": {"LOA":"Late Onset Ataxia", "P-LENS-LUX":"Primary Lens Luxation", "SCA":"Spinocerebellar Ataxia"},
	"Jagdterrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Lancashire Heeler": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Large Münsterländer": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Leonberger": {"PN":"Polyneuropathy (UK Samples Only)"},
	"McNab Shepherd": {"MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)"},
	"Miniature American Shepherd": {"AC":"Hereditary Cataract", "MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)"},
	"Miniature Bull Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Miniature Schnauzer": {"DN":"Demyelinating Neuropathy"},
	"Old English Sheepdog": {"MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)"},
	"Parson Russell Terrier": {"LOA":"Late Onset Ataxia", "P-LENS-LUX":"Primary Lens Luxation", "SCA":"Spinocerebellar Ataxia", "HUU":"Urate Stones - Uric Acid Excretion"},
	"Patterdale Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Petit Basset Griffon Vendéen": {"POAG":"Primary Open Angle Glaucoma"},
	"Pomeranian": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Rat Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Retriever (Labrador)": {"CNM":"Centronuclear Myopathy", "MCD":"Macular Corneal Dystrophy", "HUU":"Urate Stones - Uric Acid Excretion"},
	"Rough Collie": {"MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)"},
	"Russian Black Terrier": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Scottish Deerhound": {"SD":"Coagulation Factor VII Deficiency"},
	"Sealyham Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Shetland Sheepdog": {"MDR1":"MDR1 Ivermectin Sensitivity (UK Samples Only)"},
	"South African Boerbeol": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Spaniel (American Cocker)": {"PFK":"Phosphofructokinase Deficiency"},
	"Spaniel (English Springer)": {"FU_and_EP":"Combined Test - Fucosidosis and Progressive Retinal Atrophy (cord1)", "FU":"Fucosidosis", "PFK":"Phosphofructokinase Deficiency", "EP":"Progressive Retinal Atrophy (cord1)"},
	"Spanish Water Dog": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"St. Bernard": {"PN":"Polyneuropathy (UK Samples Only)"},
	"Staffordshire Bull Terrier": {"LH_and_HC":"Combined Test - L2-hydroxyglutaric aciduria and Hereditary Cataract", "AC":"Hereditary Cataract", "LH":"L-2-hydroxyglutaric aciduria"},
	"Swedish Lapphund": {"PMP":"Pompe Disease"},
	"Tenterfield Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Tibetan Spaniel": {"PRA3":"Progressive Retinal Atrophy (PRA3)"},
	"Tibetan Terrier": {"NCLB":"Neuronal Ceroid Lipofuscinosis", "P-LENS-LUX":"Primary Lens Luxation", "PRA3":"Progressive Retinal Atrophy (PRA3)", "RCD4":"Progressive Retinal Atrophy (rcd4)"},
	"Toy Fox Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Volpino Italiano": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Weimaraner": {"HUU":"Urate Stones - Uric Acid Excretion"},
	"Welsh Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
	"Yorkshire Terrier": {"P-LENS-LUX":"Primary Lens Luxation"},
};